# Generated by Django 4.2.25 on 2025-11-25 10:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sliderphotos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
