# Generated by Django 4.2.25 on 2025-11-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_roleusers_role_id_alter_roleusers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderphotos',
            name='media_id',
            field=models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, related_name='sliders_media', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='sliderphotos',
            name='sliders_id',
            field=models.ForeignKey(db_column='sliders_id', on_delete=django.db.models.deletion.CASCADE, related_name='sliders_photos', to='home.sliders'),
        ),
    ]
