# Generated by Django 5.2.8 on 2025-11-13 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sliderphotos_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentanswers',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.students'),
        ),
        migrations.AlterField(
            model_name='churchadmins',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churchadmins', to='home.students'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='home.students'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='home.students'),
        ),
        migrations.AlterField(
            model_name='students',
            name='language_id',
            field=models.ForeignKey(db_column='language_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.languages'),
        ),
        migrations.AlterField(
            model_name='studentsassignment',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='home.students'),
        ),
        migrations.AlterField(
            model_name='studentsbooks',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='home.students'),
        ),
        migrations.AlterField(
            model_name='studentsexams',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='home.students'),
        ),
        migrations.AlterField(
            model_name='studentsinstructor',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='home.students'),
        ),
        migrations.AlterField(
            model_name='studentssubjects',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='home.students'),
        ),
        migrations.AlterField(
            model_name='studentsuploads',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='home.students'),
        ),
        migrations.AlterField(
            model_name='support',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support', to='home.students'),
        ),
    ]
