# Generated by Django 4.2.25 on 2025-11-25 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu', to='home.menuitems'),
        ),
    ]
