# Generated by Django 4.2.25 on 2025-11-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_menuitems_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialibrary',
            name='file_path',
            field=models.FileField(db_column='file_path', upload_to='uploads/'),
        ),
    ]
