# Generated by Django 5.2.8 on 2025-11-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_assignmentanswers_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='language_id',
            field=models.ForeignKey(blank=True, db_column='language_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.languages'),
        ),
    ]
