# Generated by Django 4.2.25 on 2025-11-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_medialibrary_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
