# Generated by Django 5.2.8 on 2025-11-17 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_students_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
