# Generated by Django 4.2.25 on 2025-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_categories_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
