# Generated by Django 5.2.8 on 2025-11-19 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_students_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='citizenship',
            field=models.ForeignKey(blank=True, db_column='citizenship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens', to='home.countries'),
        ),
        migrations.AlterField(
            model_name='students',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='home.countries'),
        ),
        migrations.AlterField(
            model_name='students',
            name='course_applied',
            field=models.ForeignKey(blank=True, db_column='course_applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='home.courses'),
        ),
    ]
