# Generated by Django 5.2.8 on 2025-11-20 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_students_citizenship_alter_students_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpages',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.adminpages'),
        ),
        migrations.AlterField(
            model_name='assignmentanswers',
            name='assignment_id',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_answers', to='home.assignments'),
        ),
        migrations.AlterField(
            model_name='assignmentanswers',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='home.students'),
        ),
        migrations.AlterField(
            model_name='assignmentquestions',
            name='assignment_id',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_questions', to='home.assignments'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='subject_id',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_subjects', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='bookreferences',
            name='subject_id',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_references_subject', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='books',
            name='course_id',
            field=models.ForeignKey(blank=True, db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='home.courses'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='media_id',
            field=models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_media', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.categories'),
        ),
        migrations.AlterField(
            model_name='churchlogincodesettings',
            name='branches_id',
            field=models.ForeignKey(blank=True, db_column='branches_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_code_settings_branch', to='home.branches'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='media_id',
            field=models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_media', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='descriptiveanswers',
            name='assignment_id',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_descriptive_answers', to='home.assignments'),
        ),
        migrations.AlterField(
            model_name='descriptiveanswers',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='descriptive_questions_answers', to='home.descriptivequestions'),
        ),
        migrations.AlterField(
            model_name='descriptivequestions',
            name='exam_id',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_descriptive_questions', to='home.exams'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='exams_subject', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menus_id',
            field=models.ForeignKey(db_column='menus_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.menus'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='pages_id',
            field=models.ForeignKey(blank=True, db_column='pages_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items_pages', to='home.pages'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.menuitems'),
        ),
        migrations.AlterField(
            model_name='news',
            name='media_id',
            field=models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_media', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notifications', to='home.students'),
        ),
        migrations.AlterField(
            model_name='objectiveanswers',
            name='assignment_id',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_objective_answers', to='home.assignments'),
        ),
        migrations.AlterField(
            model_name='objectiveanswers',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='objective_question_answers', to='home.objectivequestions'),
        ),
        migrations.AlterField(
            model_name='objectivequestions',
            name='exam_id',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_objective_questions', to='home.exams'),
        ),
        migrations.AlterField(
            model_name='pagemedialibrary',
            name='media_id',
            field=models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, related_name='page_media_library', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='pagemedialibrary',
            name='pages_id',
            field=models.ForeignKey(db_column='pages_id', on_delete=django.db.models.deletion.CASCADE, related_name='pages_media_library', to='home.pages'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='media_id',
            field=models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_media', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='home.pages'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='video_id',
            field=models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_pages', to='home.videos'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='youtube_id',
            field=models.ForeignKey(blank=True, db_column='youtube_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_pages', to='home.youtubevideos'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='church_admin_id',
            field=models.ForeignKey(blank=True, db_column='church_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_payments', to='home.churchadmins'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='subjects_id',
            field=models.ForeignKey(blank=True, db_column='subjects_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='paymentsubjects',
            name='payment_id',
            field=models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_subjects_payment', to='home.payments'),
        ),
        migrations.AlterField(
            model_name='paymentsubjects',
            name='subject_id',
            field=models.ForeignKey(blank=True, db_column='subjects_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_subjects', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='photo_galleries_category', to='home.categories'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='media_id',
            field=models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery_media', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='photogalleryphotos',
            name='media_id',
            field=models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery_photo_media', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='photogalleryphotos',
            name='photo_gallery_id',
            field=models.ForeignKey(db_column='photo_gallery_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos_gallery_id', to='home.photogallery'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='categories_id',
            field=models.ForeignKey(blank=True, db_column='categories_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_id_photo', to='home.categories'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='media_id',
            field=models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos_medias', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='media_id',
            field=models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_post_id', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='sliderphotos',
            name='media_id',
            field=models.ForeignKey(db_column='media_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_slider_photo', to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='sliderphotos',
            name='sliders_id',
            field=models.ForeignKey(db_column='sliders_id', on_delete=django.db.models.deletion.CASCADE, related_name='sliders_photos_slider', to='home.sliders'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='staff_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffssubjects',
            name='staff_id',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects_staff', to='home.staffs'),
        ),
        migrations.AlterField(
            model_name='staffssubjects',
            name='subject_id',
            field=models.ForeignKey(blank=True, db_column='subjects_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_subjects_id', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='studentsassignment',
            name='assignment_id',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_assignment_id', to='home.assignments'),
        ),
        migrations.AlterField(
            model_name='studentsbooks',
            name='book_id',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_books_id', to='home.books'),
        ),
        migrations.AlterField(
            model_name='studentsexams',
            name='exam_id',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_id', to='home.exams'),
        ),
        migrations.AlterField(
            model_name='studentssubjects',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='students_subject_id', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='studentsuploads',
            name='upload_id',
            field=models.ForeignKey(db_column='upload_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_uploads_id', to='home.uploads'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='branches_id',
            field=models.ForeignKey(db_column='branches_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects_branch_id', to='home.branches'),
        ),
        migrations.AlterField(
            model_name='support',
            name='student_id',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_student', to='home.students'),
        ),
        migrations.AlterField(
            model_name='support',
            name='subjects_id',
            field=models.ForeignKey(blank=True, db_column='subjects_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_entries', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='supportreplies',
            name='support_id',
            field=models.ForeignKey(db_column='support_id', on_delete=django.db.models.deletion.CASCADE, related_name='replies_support', to='home.support'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='media_id',
            field=models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='subjects_uploads', to='home.subjects'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='video_id',
            field=models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads_video', to='home.videos'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='youtube_id',
            field=models.ForeignKey(blank=True, db_column='youtube_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_uploads', to='home.youtubevideos'),
        ),
        migrations.AlterField(
            model_name='users',
            name='church_admin_id',
            field=models.ForeignKey(blank=True, db_column='church_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='home.churchadmins'),
        ),
        migrations.AlterField(
            model_name='users',
            name='locked_exam',
            field=models.ForeignKey(blank=True, db_column='locked_exam', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.exams'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='categories_id',
            field=models.ForeignKey(blank=True, db_column='categories_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_categories', to='home.categories'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='media_id',
            field=models.ForeignKey(blank=True, db_column='media_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.medialibrary'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='youtube_id',
            field=models.ForeignKey(blank=True, db_column='youtube_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_videos', to='home.youtubevideos'),
        ),
    ]
