# Generated by Django 4.2.25 on 2025-11-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_languages_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
