# Generated by Django 4.2.25 on 2025-11-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_languages_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
