# Generated by Django 4.2.25 on 2025-11-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_languages_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
