# Generated by Django 4.2.25 on 2025-11-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_subjects_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branches',
            name='is_associate_degree',
            field=models.BooleanField(default=False),
        ),
    ]
