# Generated by Django 4.2.25 on 2025-12-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_branches_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exam_type',
            field=models.CharField(choices=[('descriptive', 'Descriptive'), ('objective', 'Objective')], max_length=20),
        ),
    ]
