# Generated by Django 4.2.25 on 2025-12-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_exams_deleted_at_alter_exams_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
