# Generated by Django 4.2.25 on 2025-12-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_assignments_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_type',
            field=models.CharField(choices=[('paper_upload', 'Paper Upload type'), ('paper_submit', 'Paper Submit type')], max_length=250),
        ),
    ]
