# Generated by Django 4.2.25 on 2025-12-01 06:29

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_assignments_assignment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
