# Generated by Django 4.2.25 on 2025-12-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_staffs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Uploads/'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
