# Generated by Django 4.2.25 on 2025-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_staffs_image_alter_staffs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreferences',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookreferences',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Uploads/staffs/'),
        ),
    ]
