# Generated by Django 4.2.25 on 2025-12-01 09:35

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_bookreferences_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreferences',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookreferences',
            name='reference_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.medialibrary'),
        ),
    ]
