# Generated by Django 4.2.25 on 2025-12-01 09:46

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_bookreferences_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreferences',
            name='format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('note', 'Note')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bookreferences',
            name='reference_note',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
