# Generated by Django 4.2.25 on 2025-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_bookreferences_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='certificate1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/certificates/1/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='certificate2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/certificates/2/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='certificate3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/certificates/3/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='certificate4',
            field=models.FileField(blank=True, null=True, upload_to='uploads/certificates/4/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='certificate5',
            field=models.FileField(blank=True, null=True, upload_to='uploads/certificates/5/'),
        ),
    ]
