# Generated by Django 4.2.25 on 2025-12-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_support_deleted_at_alter_students_certificate1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolehaspermissions',
            old_name='permission_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rolehaspermissions',
            old_name='role_id',
            new_name='role_is',
        ),
        migrations.AddField(
            model_name='rolehaspermissions',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.permissions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolehaspermissions',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.roles'),
            preserve_default=False,
        ),
    ]
