# Generated by Django 4.2.25 on 2025-12-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_permission_id_rolehaspermissions_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolehaspermissions',
            unique_together={('permission', 'role')},
        ),
        migrations.RemoveField(
            model_name='rolehaspermissions',
            name='role_is',
        ),
    ]
