# Generated by Django 4.2.25 on 2025-12-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_rolehaspermissions_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
