# Generated by Django 4.2.25 on 2025-12-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_roles_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchadmins',
            name='church_code_id',
        ),
        migrations.AddField(
            model_name='churchadmins',
            name='church_code',
            field=models.ForeignKey(db_column='church_code_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='church_admins', to='home.churchlogincodesettings'),
            preserve_default=False,
        ),
    ]
