# Generated by Django 4.2.25 on 2025-12-19 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_churchadmins_church_code_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='home.bookreferences'),
        ),
    ]
