# Generated by Django 5.2.4 on 2025-12-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_studentsbooks_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinstructor',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_instructors', to='home.subjects'),
        ),
    ]
