# Generated by Django 5.2.4 on 2025-12-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_studentsinstructor_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsexams',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exams', to='home.courses'),
        ),
        migrations.AddField(
            model_name='studentsexams',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exams', to='home.subjects'),
        ),
    ]
