# Generated by Django 4.2.25 on 2025-12-20 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_studentsexams_course_studentsexams_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptiveanswers',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descriptive_answers', to='home.studentsexams'),
        ),
        migrations.AlterField(
            model_name='objectiveanswers',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='objective_answers', to='home.studentsexams'),
        ),
    ]
