# Generated by Django 4.2.25 on 2025-12-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_descriptiveanswers_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentanswers',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/assignments/'),
        ),
    ]
