# Generated by Django 5.2.4 on 2026-01-01 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_assignmentanswers_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsbooks',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsbooks',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
