# Generated by Django 4.2.25 on 2026-01-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_studentsbooks_is_approved_studentsbooks_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
