# Generated by Django 5.1.4 on 2026-02-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_courses_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolehaspermissions",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
