# Generated by Django 5.2.7 on 2026-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_alter_rolehaspermissions_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminpages",
            options={"managed": True, "ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="assignments",
            options={"managed": True, "ordering": ["assignment_name"]},
        ),
        migrations.AlterModelOptions(
            name="bookreferences",
            options={"managed": True, "ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="books",
            options={"managed": True, "ordering": ["book_name"]},
        ),
        migrations.AlterModelOptions(
            name="branches",
            options={"managed": True, "ordering": ["branch_name"]},
        ),
        migrations.AlterModelOptions(
            name="categories",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="churchadmins",
            options={"managed": True, "ordering": ["name_of_church"]},
        ),
        migrations.AlterModelOptions(
            name="churchlogincodesettings",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="countries",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="courses",
            options={"managed": True, "ordering": ["course_name"]},
        ),
        migrations.AlterModelOptions(
            name="exams",
            options={"managed": True, "ordering": ["exam_name"]},
        ),
        migrations.AlterModelOptions(
            name="languages",
            options={"managed": True, "ordering": ["language_name"]},
        ),
        migrations.AlterModelOptions(
            name="menuitems",
            options={"managed": True, "ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="menus",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"managed": True, "ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="pages",
            options={"managed": True, "ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="qualifications",
            options={"managed": True, "ordering": ["qualification_name"]},
        ),
        migrations.AlterModelOptions(
            name="roles",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="sliders",
            options={"managed": True, "ordering": ["slider_name"]},
        ),
        migrations.AlterModelOptions(
            name="staffs",
            options={"managed": True, "ordering": ["staff_name"]},
        ),
        migrations.AlterModelOptions(
            name="students",
            options={"managed": True, "ordering": ["first_name"]},
        ),
        migrations.AlterModelOptions(
            name="subjects",
            options={"managed": True, "ordering": ["subject_name"]},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="uploads",
            options={"managed": True, "ordering": ["upload_name"]},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"managed": True, "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="videos",
            options={"managed": True, "ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="studentsexams",
            name="is_rescheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="support",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
