# Generated by Django 6.0.1 on 2026-04-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_alter_adminpages_options_alter_assignments_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchAdminApplication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name_of_church", models.CharField(max_length=250)),
                (
                    "name_of_pastor",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("church_address", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church_code_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.churchlogincodesettings",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_admin_applications",
                        to="home.students",
                    ),
                ),
            ],
            options={
                "db_table": "church_admin_applications",
                "managed": True,
            },
        ),
    ]
