# Generated by Django 6.0.1 on 2026-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_churchadminapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchadmins",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
