# Generated by Django 6.0.1 on 2026-06-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_churchadmins_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="fees",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
