# Generated by Django 6.0.1 on 2026-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_courses_fees_students_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsexams",
            name="attempt_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="studentsexams",
            name="is_retest",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentsexams",
            name="retest_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentsexams",
            name="retest_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
