# Generated by Django 6.0.1 on 2026-06-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_studentsexams_attempt_number_studentsexams_is_retest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsexams",
            name="retest_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentsexams",
            name="retest_paid",
            field=models.BooleanField(default=False),
        ),
    ]
