# Generated by Django 6.0.1 on 2026-07-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_studentsexams_retest_fee_studentsexams_retest_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentanswers",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers",
                to="home.assignmentquestions",
            ),
        ),
    ]
